server:
<<<<<<< HEAD
  port: 8081
=======
  port: 8080
>>>>>>> d6b2170e894f9c4ef49b47da8a821dea6b3d6b1a

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/users
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus